# runtime: nodejs # or another supported version
# env: flex
# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10

# instance_class: F2

# env_variables:
#   BUCKET_NAME: "southerntranspride"

# handlers:
# - url: /
#   static_dir: /
# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto
runtime: nodejs12
handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html
